### ISSUE TITLE
Implment the required new methods for Puppet

### ISSUE THREAD

**Issue by zixia** [linyimin-bupt/wechaty-puppet-ioscat#10]
@linyimin-bupt I had just upgrade the puppet dependence to the latest v0.13.

There are several required new Abstract methods in the Puppet class need to be implemented, so please have a look and fix them as well.

Current the CI test will fail, after the fix, it should turn to green again.

Related commit: <https://github.com/linyimin-bupt/wechaty-puppet-ioscat/commit/f2339c3fb5ab42c7d39b32476773fe09c382ba4c>

**Comment by linyimin-bupt** [comment]
OK

**Comment by linyimin-bupt** [comment]
I'm sorry, I had other job to finish recently, and had no time to fix the Related issues, I will fix them tomorrow.

**Comment by zixia** [comment]
No problem.

It's no rush and please take it easy.

**Comment by zixia** [comment]
It seems that you had already fixed all those problems.

Can we close this issue for now?

**Comment by linyimin-bupt** [comment]
OK, Thanks very much.I will notice this, and try to make it better.
