### ISSUE TITLE
All images in the Wiki page is `404` now.

### ISSUE THREAD

**Issue by zixia** [linyimin-bupt/wechaty-puppet-ioscat#11]
See: https://github.com/linyimin-bupt/wechaty-puppet-ioscat/wiki/PuppetIoscat-usage

**Comment by linyimin-bupt** [comment]
I have fixed it, It's my picture server crashed, and have put the pictures to aliyun OSS, and this will not happened again.

**Comment by zixia** [comment]
I'd like to suggest that you put all the pictures in to the `/docs/images/` in your repository, and link all of them from there, to prevent the future 404 errors.

**Comment by linyimin-bupt** [comment]
OK, I will do this when next commit.

**Comment by linyimin-bupt** [comment]
Thanks very much.
