### ISSUE TITLE
Suggest a better logo...

### ISSUE THREAD

**Issue by zixia** [linyimin-bupt/wechaty-puppet-ioscat#2]
![](https://medias.pylones.com/6050-large_default/charabia-mouse-pad-with-wrist-support.jpg)

![](https://ae01.alicdn.com/kf/HTB1dUcYLVXXXXblXVXXq6xXFXXXQ/Muismat-Hot-Kat-Foto-Antislip-Laptop-PC-Muizen-Pad-Mat-Mousepad-Voor-Optical-Mouse-Promotie.jpg)

**Comment by linyimin-bupt** [comment]
The second is cool.
