### ISSUE TITLE
Write a simple tutorial for introduce how to use puppet-ioscat

### ISSUE THREAD

**Issue by zixia** [linyimin-bupt/wechaty-puppet-ioscat#5]
The goal is to:

1. let me be able to start using it first, then 
1. call for more volunteers to join

**Comment by linyimin-bupt** [comment]
OK, when the apis are fixed, I will write it

**Comment by vipzhicheng** [comment]
Looking forward the tutorial, I just tried to use this in wechaty-getting-started, but failed to launch. I don't know what the token is, and any other necessary options need to be set.

**Comment by linyimin-bupt** [comment]
https://github.com/linyimin-bupt/wechaty-puppet-ioscat/wiki/PuppetIoscat-usage
