### ISSUE TITLE
UDID和kUDID是否一致

### ISSUE THREAD

**Issue by wuying8** [linyimin-bupt/wechaty-puppet-ioscat#6]
在爱思助手上获取到的UDID和设备精灵获取的是否一致，因为在cydia没有找到设备精灵，是否需要添加指定源？

**Comment by linyimin-bupt** [comment]
应该是一致的,但是按照接口第三方的说法,没有安装设备精灵可能会无法使用,可以先尝试一下

**Comment by wuying8** [comment]
要安装设备精灵的话是需要添加哪个源呢？

**Comment by linyimin-bupt** [comment]
I use the [紫云平台](http://apt.mofanbaby.com)http://apt.mofanbaby.com

**Comment by zixia** [comment]
Should put this information into Wiki.

**Comment by linyimin0812** [comment]
I'm sorry, I just see it.
